<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  Reads every Mod/Languages/French/DefInjected/**/*.xml key. For each key, resolves the
  English text directly from the shipped Def in Mod/Defs (label/description/customLabel
  fields resolved by dotted path against the Def's own XML) — MegabeesRenew has no
  Mod/Languages/English folder, English being the game's native fallback in the Defs.

  Original column: the mod has no source language other than English (ATTRIBUTION.md
  names no other original text), so Original equals English, stated once at the top
  rather than on every row.

  Model: FoodCourt/_tools/Generate-FrenchReview.ps1 (TRANSLATIONS.md, reference script).
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

function Resolve-DefField($defsRoot, [string]$defTag, [string]$key) {
    # key looks like "DefName.field" or "DefName.corePart.parts.NAME.customLabel"
    # defTag (e.g. ThingDef, PawnKindDef, BodyDef, BodyPartDef) disambiguates defNames
    # reused across different Def types (Megabee is a ThingDef, a PawnKindDef and a BodyDef).
    $parts = $key -split '\.'
    $defName = $parts[0]
    $rest = $parts[1..($parts.Length - 1)]
    $cacheKey = "$defTag/$defName"
    if (-not $script:defCache.ContainsKey($cacheKey)) {
        $found = $null
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            $node = $x.SelectSingleNode("//$defTag[defName='$defName']")
            if ($node) { $found = $node; break }
        }
        $script:defCache[$cacheKey] = $found
    }
    $node = $script:defCache[$cacheKey]
    if (-not $node) { return $null }
    $cur = $node
    $i = 0
    while ($i -lt $rest.Count) {
        $p = $rest[$i]
        if ($null -eq $cur) { return $null }
        if ($p -match '^\d+$') {
            $children = @($cur.ChildNodes | Where-Object { $_.NodeType -eq 'Element' })
            $idx = [int]$p
            if ($idx -ge $children.Count) { return $null }
            $cur = $children[$idx]
            $i++
            continue
        }
        $next = $cur.$p
        if ($null -eq $next) { return $null }
        # A wrapper element (parts, tools, lifeStages...) holds its entries as <li> children,
        # one XmlElement when there is a single entry, an array when there are several: the
        # following path segment then selects one by label/customLabel/def.
        $liList = $null
        if ($next -is [System.Xml.XmlElement]) { $liList = $next.li }
        if (($null -ne $liList) -and ($i + 1 -lt $rest.Count)) {
            $target = $rest[$i + 1]
            $target2 = $target -replace '_', ' '
            $match = $null
            foreach ($li in @($liList)) {
                if ($li.label -eq $target -or $li.customLabel -eq $target -or $li.def -eq $target -or
                    $li.label -eq $target2 -or $li.customLabel -eq $target2 -or $li.def -eq $target2) { $match = $li; break }
            }
            if (-not $match) { return $null }
            $cur = $match
            $i += 2
            continue
        }
        $cur = $next
        $i++
    }
    if ($cur -is [System.Xml.XmlElement]) { return $cur.InnerText }
    if ($cur) { return [string]$cur }
    return $null
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French'
$defsRoot = Join-Path $Root 'Mod/Defs'
$script:defFiles = Get-ChildItem $defsRoot -Recurse -Filter *.xml | ForEach-Object { $_.FullName }
$script:defCache = @{}

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by ``_tools/Generate-FrenchReview.ps1`` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** MegabeesRenew has no source language other")
[void]$out.AppendLine("than English (ATTRIBUTION.md names none); English is the original for every row.")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: working tree after the gender-agreement rule of 2026-09-30.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    [void]$out.AppendLine("| Key or path | Original | English | French |")
    [void]$out.AppendLine("|---|---|---|---|")
    $defTag = Split-Path (Split-Path $rel -Parent) -Leaf
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $orig = Resolve-DefField $defsRoot $defTag $key
        $en = $orig
        if ($null -eq $orig) { $orig = '*(not found -- check by hand)*'; $en = $orig }
        $flag = if ($fr -match '\?\?\?|TODO|\{PAWN_gender' -and $fr -notmatch '\{PAWN_gender \? ') { ' | ?' } else { '' }
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell$flag |")
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
